const actionsTypes = {
    SET_USERS: 'SET_USERS',
    SET_USER: 'SET_USER',
    SET_ROLE_OPTIONS: 'SET_ROLE_OPTIONS',
    SET_LOADING_USERS_LIST: 'SET_LOADING_USER_LIST',
    SET_LOADING_USER: 'SET_LOADING_USER',
    SET_LOADING_CREATE_USER: 'SET_LOADING_CREATE_USER',
    SET_LOADING_EDIT_USER: 'SET_LOADING_EDIT_USER',
}

export { actionsTypes };